riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode machine --seed 1 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode machine --seed 2 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode machine --seed 1 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode machine --seed 2 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode machine --seed 1 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode machine --seed 2 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode machine --seed 1 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode machine --seed 2 --run_dir testsuite/zifencei/machine
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode super --seed 1 --run_dir testsuite/zifencei/super_disable
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode super --seed 2 --run_dir testsuite/zifencei/super_disable
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode super --seed 1 --run_dir testsuite/zifencei/super_sv39
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode super --seed 2 --run_dir testsuite/zifencei/super_sv39
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode super --seed 1 --run_dir testsuite/zifencei/super_sv48
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode super --seed 2 --run_dir testsuite/zifencei/super_sv48
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode super --seed 1 --run_dir testsuite/zifencei/super_sv57
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode super --seed 2 --run_dir testsuite/zifencei/super_sv57
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode user --seed 1 --run_dir testsuite/zifencei/user_disable
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode user --seed 2 --run_dir testsuite/zifencei/user_disable
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode user --seed 1 --run_dir testsuite/zifencei/user_sv39
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode user --seed 2 --run_dir testsuite/zifencei/user_sv39
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode user --seed 1 --run_dir testsuite/zifencei/user_sv48
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode user --seed 2 --run_dir testsuite/zifencei/user_sv48
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode user --seed 1 --run_dir testsuite/zifencei/user_sv57
riescuec --mode tp --test_plan zifencei --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode user --seed 2 --run_dir testsuite/zifencei/user_sv57
