riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode machine --seed 1 --run_dir testsuite/zjpm/machine
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode machine --seed 2 --run_dir testsuite/zjpm/machine
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode machine --seed 1 --run_dir testsuite/zjpm/machine
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode machine --seed 2 --run_dir testsuite/zjpm/machine
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode machine --seed 1 --run_dir testsuite/zjpm/machine
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode machine --seed 2 --run_dir testsuite/zjpm/machine
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode super --seed 1 --run_dir testsuite/zjpm/super_sv39
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode super --seed 2 --run_dir testsuite/zjpm/super_sv39
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode super --seed 1 --run_dir testsuite/zjpm/super_sv48
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode super --seed 2 --run_dir testsuite/zjpm/super_sv48
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode super --seed 1 --run_dir testsuite/zjpm/super_sv57
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode super --seed 2 --run_dir testsuite/zjpm/super_sv57
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode user --seed 1 --run_dir testsuite/zjpm/user_sv39
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode user --seed 2 --run_dir testsuite/zjpm/user_sv39
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode user --seed 1 --run_dir testsuite/zjpm/user_sv48
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode user --seed 2 --run_dir testsuite/zjpm/user_sv48
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode user --seed 1 --run_dir testsuite/zjpm/user_sv57
riescuec --mode tp --test_plan zjpm --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode user --seed 2 --run_dir testsuite/zjpm/user_sv57
