riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode super --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_disable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode super --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_disable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode super --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_sv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode super --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_sv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode super --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_sv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode super --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_sv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode super --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_sv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode super --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/super_sv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode user --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_disable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_priv_mode user --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_disable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode user --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_sv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_priv_mode user --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_sv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode user --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_sv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_priv_mode user --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_sv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode user --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_sv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_priv_mode user --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/user_sv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_disable_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv39_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv48_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode disable --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv39 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv48 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv57 --test_priv_mode super --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/super_sv57_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode disable --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_disable_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv39 --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv39_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv48 --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv48_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode disable --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gdisable
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv39 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gsv39
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv48 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gsv48
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 1 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gsv57
riescuec --mode tp --test_plan hypervisor_paging --print_rvcp_passed --print_rvcp_failed --test_paging_mode sv57 --test_paging_g_mode sv57 --test_priv_mode user --test_env virtualized --seed 2 --repeat_times 1 --cpuconfig ../custom_conf.json --run_dir testsuite/hypervisor_paging/virtualized/user_sv57_gsv57
